/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package water_refilling_station;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Enrie John B. Edem
 */
public class Sales extends javax.swing.JInternalFrame {

    public Connection con = null;
    public Statement st = null;

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        viewdata();
    }

    public void viewdata() {
        try {
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            con = XConnect.Connect();
            String sql = "select *from deliver";
            st = con.createStatement();
            ResultSet rss = st.executeQuery(sql);
            mod.setRowCount(0);
            while (rss.next()) {
                mod.addRow(new Object[]{rss.getString("Name"), rss.getString("Number"), rss.getString("Address"), rss.getInt("Bottles"), rss.getDouble("Total")});
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void viewdatas() {
        try {
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            con = XConnect.Connect();
            String sql = "select *from pickup";
            st = con.createStatement();
            ResultSet rss = st.executeQuery(sql);
            mod.setRowCount(0);
            while (rss.next()) {
                mod.addRow(new Object[]{rss.getString("Name"), rss.getString("Contact"), rss.getInt("Bottles"), rss.getDouble("Total")});
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void delivered() {
        try {
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            con = XConnect.Connect();
            String sql = "select *from delivered";
            st = con.createStatement();
            ResultSet rss = st.executeQuery(sql);
            mod.setRowCount(0);
            while (rss.next()) {
                mod.addRow(new Object[]{rss.getString("Name"), rss.getString("address"), rss.getString("total"), rss.getString("Status")});
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printdel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("SALES REPORT");
        setPreferredSize(new java.awt.Dimension(687, 558));

        printdel.setBackground(new java.awt.Color(0, 255, 51));
        printdel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        printdel.setText("PRINT DELIVERY REPORT");
        printdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printdelActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact", "Address", "Bottle", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DELIVERY");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DELIVERY\t", "PICKUP", "DELIVERED" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("NAME SEARCH");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(436, 436, 436))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3)
                                .addComponent(printdel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printdel)
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printdelActionPerformed
        int a = jComboBox1.getSelectedIndex();
        if (a == 0) {
            try {
                JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Enrie John B. Edem\\Documents\\NetBeansProjects\\Water_Refilling_Station\\src\\water_refilling_station\\report1.jrxml");
                String query = "SELECT *FROM `deliver`";

                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesign.setQuery(updateQuery);
                HashMap para = new HashMap();

                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (JRException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (a == 1) {
            try {
                JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Enrie John B. Edem\\Documents\\NetBeansProjects\\Water_Refilling_Station\\src\\water_refilling_station\\report2.jrxml");
                String query = "SELECT *FROM `pickup`";

                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesign.setQuery(updateQuery);
                HashMap para = new HashMap();

                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (JRException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (a == 2) {
            try {
                JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Enrie John B. Edem\\Documents\\NetBeansProjects\\Water_Refilling_Station\\src\\water_refilling_station\\report3.jrxml");
                String query = "SELECT *FROM `delivered`";

                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesign.setQuery(updateQuery);
                HashMap para = new HashMap();

                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (JRException ex) {
                Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_printdelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int a = jComboBox1.getSelectedIndex();
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        if (a == 0) {
            jLabel3.setText("DELIVERY");
            printdel.setText("PRINT DELIVERY REPORT");
            mod.setColumnCount(0);
            mod.addColumn("Name");
            mod.addColumn("Contact");
            mod.addColumn("Address");
            mod.addColumn("Bottle");
            mod.addColumn("Total");
            viewdata();
        } else if (a == 1) {
            jLabel3.setText("PICKUP");
            printdel.setText("PRINT PICKUP REPORT");
            mod.setColumnCount(0);
            mod.addColumn("Name");
            mod.addColumn("Contact");
            mod.addColumn("Bottle");
            mod.addColumn("Total");
            viewdatas();
        } else if (a == 2) {
            jLabel3.setText("DELIVERED");
            printdel.setText("PRINT DELIVERED REPORT");
            mod.setColumnCount(0);
            mod.addColumn("Name");
            mod.addColumn("Address");
            mod.addColumn("Total");
            mod.addColumn("Status");
            delivered();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        int a = jComboBox1.getSelectedIndex();
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        String ty = jTextField1.getText();
        if (a == 0) {
            try {             
                con = XConnect.Connect();    
                String sql = "select * from deliver where Name Like  '" + ty + "%'";
                st = con.createStatement();
                ResultSet rss = st.executeQuery(sql);
                mod.setRowCount(0);
                while (rss.next()) {
                    mod.addRow(new Object[]{rss.getString("Name"), rss.getString("Number"), rss.getString("Address"), rss.getInt("Bottles"), rss.getDouble("Total")});
                    jTextArea1.setText(rss.getString("Name"));
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (a == 1) {
            try {
                con = XConnect.Connect();
                String sql = "select * from pickup where Name Like  '" + ty + "%'";
                st = con.createStatement();
                ResultSet rss = st.executeQuery(sql);
                mod.setRowCount(0);
                while (rss.next()) {
                    mod.addRow(new Object[]{rss.getString("Name"), rss.getString("Contact"), rss.getInt("Bottles"), rss.getDouble("Total")});
                    jTextArea1.setText(rss.getString("Name"));
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (a == 2) {
            try {
                con = XConnect.Connect();
                String sql = "select * from delivered where Name Like  '" + ty + "%'";
                st = con.createStatement();
                ResultSet rss = st.executeQuery(sql);
                mod.setRowCount(0);
                while (rss.next()) {
                    mod.addRow(new Object[]{rss.getString("Name"), rss.getString("address"), rss.getString("total"), rss.getString("Status")});
                    jTextArea1.setText(rss.getString("Name"));
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }if (ty.length() == 0) {
                jTextArea1.setText(null);
            }
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton printdel;
    // End of variables declaration//GEN-END:variables
}
